# Generated by Django 2.2.2 on 2019-07-17 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('class_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Class')),
                ('course_enrolled', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
