# Generated by Django 2.2.2 on 2019-08-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0008_auto_20190815_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=20)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Class')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Unit')),
            ],
            options={
                'verbose_name_plural': 'Timetable',
            },
        ),
    ]
