# Generated by Django 2.2.2 on 2019-08-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
