# Generated by Django 2.2.2 on 2019-08-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190817_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
