# Generated by Django 2.2.2 on 2019-08-17 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20190817_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='start_time',
            new_name='start',
        ),
    ]
