# Generated by Django 2.2.2 on 2019-08-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20190817_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
