# Generated by Django 2.2.2 on 2019-08-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
