# Generated by Django 2.2.2 on 2019-08-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start',
            field=models.TimeField(),
        ),
    ]
