# Generated by Django 2.2.2 on 2019-07-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='class_registered',
        ),
    ]
