# Generated by Django 2.2.2 on 2019-08-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20190814_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
