# Generated by Django 2.2.2 on 2019-08-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_lecturer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdetail',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Lecturer'),
        ),
    ]
