# Generated by Django 2.2.2 on 2019-08-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_unitdetail_lecturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='unitdetail',
            name='resources',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
