# Generated by Django 2.2.2 on 2019-08-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_auto_20190815_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOutline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=10)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Unit')),
            ],
        ),
    ]
