# Generated by Django 2.2.2 on 2019-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_courseoutline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
