# Generated by Django 2.2.2 on 2019-08-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_auto_20190818_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.UnitRegistration'),
        ),
    ]
