# Generated by Django 2.2.2 on 2019-08-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20190818_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('due_date', models.DateTimeField()),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Class')),
                ('lec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Lecturer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Unit')),
            ],
        ),
    ]
