# Generated by Django 2.2.2 on 2019-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190718_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time_posted',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='date_posted',
            field=models.DateField(),
        ),
    ]
